name: Backend CI


on:
  pull_request:
    branches:
      - main
  workflow_dispatch



permissions:
  contents: read
  id-token: write



jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd Backend
          pipenv run lint


  Test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd Backend
          pipenv install
          pipenv run test


  Build:
    runs-on: ubuntu-latest
    needs: [ Lint, Test ]
    steps:
      - run: |
          cd Backend
          docker build --tag mp-backend:latest .

