name: Backend CI


on:
  pull_request:
    branches:
      - main
    paths:
      - Backend/**
  workflow_dispatch:



permissions:
  contents: read
  id-token: write



jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Lint
        run: |
          cd Backend
          pipenv run lint


  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Test
        run: |
          cd Backend
          pipenv install
          pipenv run test


  Build:
    runs-on: ubuntu-latest
    needs: [ Lint, Test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Backend
        run: |
          cd Backend
          docker build --tag mp-backend:latest .

