name: Backend CI


on:
  pull_request:
    branches:
      - main
    paths:
      - Backend/**
  workflow_dispatch:



permissions:
  contents: read
  id-token: write



jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install pipenv
        run: pip install pipenv

      - name: Run Lint
        run: |
          cd Backend
          pipenv install --dev
          pipenv run lint


  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install pipenv
        run: pip install pipenv

      - name: Run Test
        run: |
          cd Backend
          pipenv install
          pipenv run test


  Build:
    runs-on: ubuntu-latest
    needs: [ Lint, Test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Backend
        run: |
          cd Backend
          docker build --tag mp-backend:latest .

