name: Frontend CI


on:
  pull_request:
    branches:
      - main
  workflow_dispatch



permissions:
  contents: read
  id-token: write



jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd Frontend
          npm run lint


  Test:
    runs-on: ubuntu-latest
    steps:
      - run: |
        cd Frontend
        nvm use
        npm ci
        CI=true npm test


  Build:
    runs-on: ubuntu-latest
    needs: [ Lint, Test ]
    steps:
      - run: |
          cd Frontend
          npm ci
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .

