name: Frontend CI


on:
  pull_request:
    branches:
      - main
    paths:
      - Frontend/**
  workflow_dispatch:



permissions:
  contents: read
  id-token: write



jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Lint
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd Frontend
          npm ci
          npm run lint


  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Test
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd Frontend
          nvm install
          nvm use
          npm ci
          CI=true npm test


  Build:
    runs-on: ubuntu-latest
    needs: [ Lint, Test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Frontdend
        run: |
          cd Frontend
          npm ci
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .

